using UnityEngine;
using System.Collections;
using UnityEngine.AI;
using UnityEngine.UI;

public class Enemy1Behaviour : MonoBehaviour
{
    // Basic Stats
    public float health;
    public float focus;

    public float maxHealth = 100f;
    public float maxFocus = 100f;

    // Regeneration
    public float focusRegenRate = 2f;
    public float healthRegenRate = 0f;

    // Damage Related
    public float damage;
    public float damageMultiplier;

    // Armour
    public float armour;

    // UI
    [Header("Set in the inspector!")]
    public Slider healthBar;
    public Slider focusBar;

    // Navmesh
    [Header("Navmesh Related")]
    public Transform target;
    private Vector3 _destination;
    private NavMeshAgent _agent;
    private float _distanceDifference;

    // Attack
    private float _attackDistance;
    public bool canAttack;
    private float _attackCooldown;
    public float focustCostPerAttack;

    // SetStandards
    public bool setStandards;

    // Animator
    private Animator animator;

    // Script reference
    [Header("Set in the inspector!")]
    public GameObject animatorObjectReference;
    public EnemyWeapon enemyWeaponScript;

    private void Awake()
    {
        animator = animatorObjectReference.GetComponent<Animator>();
    }

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        SetStandards();

        SetupNavmesh();
    }

    void Update()
    {
        UpdateSliders();

        UpdateTargetLocation();

        if (Vector3.Distance(transform.position, target.position) <= _attackDistance && canAttack && focus >= focustCostPerAttack)
        {
            canAttack = false; // Prevent double starting
            StartCoroutine(AttackCooldown(_attackCooldown));
        }

        RegenerateFocus();
    }

    /// <summary>
    /// Sets the standards in the inspector if the boolean has been turned to true
    /// </summary>
    private void SetStandards()
    {
        if (setStandards)
        {
            maxHealth = 100f;
            maxFocus = 100f;
            focusRegenRate = 2f;
            healthRegenRate = 0f;
            damage = 5f;
            damageMultiplier = 1f;
            armour = 0f;
            _attackCooldown = 3f;
            focustCostPerAttack = 10;
            _attackDistance = 2.5f;

            health = maxHealth;
            focus = maxFocus;
        }
    }

    /// <summary>
    /// Focus will be generated by the value of focusRegenRate each second
    /// </summary>
    private void RegenerateFocus()
    {
        if (focus < maxFocus)
        {
            focus += focusRegenRate * Time.deltaTime; // Regenerates focus per second
            focus = Mathf.Clamp(focus, 0f, maxFocus); // Prevent overfilling
        }
    }

    /// <summary>
    /// This will set up the values, connects object/components, etc that are needed for the navmesh player following to work
    /// </summary>
    private void SetupNavmesh()
    {
        _distanceDifference = 0.1f;
        target = GameObject.FindWithTag("Player").transform; //  Sets the target of the enemy
        _agent = GetComponent<NavMeshAgent>(); // Tells the script that agent is the NavMeshAgent component of the object this script is attached to
        _destination = _agent.destination;
    }

    /// <summary>
    /// Updates the value of the sliders to the value of the the player's variables
    /// </summary>
    private void UpdateSliders()
    {
        healthBar.value = health;
        focusBar.value = focus;
    }

    /// <summary>
    /// Updates the location of the target so the agent knows where to go
    /// </summary>
    private void UpdateTargetLocation()
    {
        transform.LookAt(target);

        if (Vector3.Distance(_destination, target.position) > _distanceDifference) // Updates when the difference is bigger then the value of distanceDifference
        {
            _destination = target.position; // Updates the vector destination of the agent to the position of the target
            _agent.destination = _destination; // Sets the agents's destination to the value of destination
        }
    }

    /// <summary>
    /// 
    /// </summary>
    /// <param name="timerSeconds"></param>
    /// <returns></returns>
    public IEnumerator AttackCooldown(float timerSeconds)
    {
        canAttack = false; // It gets set to false twice for extra safety
        enemyWeaponScript.hasHit = false; // Makes sure the player can be hit again
        
        animator.SetTrigger("Attack"); // Triggers the attack animation

        focus -= focustCostPerAttack; // Makes the attack cost focus

        // Wait for the cooldown
        yield return new WaitForSeconds(timerSeconds);

        canAttack = true;
    }
    private void OnDrawGizmos()
    {
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position, _attackDistance);
    }
}
